# Generated by Django 4.0 on 2022-01-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(blank=True, max_length=40)),
                ('answer_line', models.CharField(max_length=30, verbose_name='Варiант 1')),
                ('answer_column', models.CharField(max_length=30, verbose_name='Варiант 2')),
            ],
            options={
                'verbose_name': 'Варiанти відповіді',
                'verbose_name_plural': 'Варiанти відповіді',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(blank=True, max_length=40)),
                ('variant1', models.CharField(max_length=30, verbose_name='Варiант 1')),
                ('variant2', models.CharField(max_length=30, verbose_name='Варiант 2')),
                ('variant3', models.CharField(max_length=30, verbose_name='Варiант 3')),
                ('variant4', models.CharField(max_length=30, verbose_name='Варiант 4')),
            ],
            options={
                'verbose_name': 'Варiанти відповіді',
                'verbose_name_plural': 'Варiанти відповіді',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Short_answer'), ('SC', 'Single_choise'), ('MC', 'Multiple_choise'), ('G', 'Grid_answer')], default='S', max_length=2, verbose_name='Тип питання')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип питання',
                'verbose_name_plural': 'Типи питань',
            },
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Варiанти відповіді',
                'verbose_name_plural': 'Варiанти відповіді',
            },
        ),
        migrations.CreateModel(
            name='SingleChoiseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(blank=True, max_length=40)),
                ('variant1', models.CharField(max_length=30, verbose_name='Варiант 1')),
                ('variant2', models.CharField(max_length=30, verbose_name='Варiант 2')),
                ('variant3', models.CharField(max_length=30, verbose_name='Варiант 3')),
                ('variant4', models.CharField(max_length=30, verbose_name='Варiант 4')),
            ],
            options={
                'verbose_name': 'Варiанти відповіді',
                'verbose_name_plural': 'Варiанти відповіді',
            },
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_picture',
            new_name='question_image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='result',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='testeduser',
            name='age',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='testeduser',
            name='login',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='answer',
            name='point',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
        migrations.AddField(
            model_name='singlechoiseanswer',
            name='question_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.question'),
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='question_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.question'),
        ),
        migrations.AddField(
            model_name='multiplechoiseanswer',
            name='question_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.question'),
        ),
        migrations.AddField(
            model_name='gridanswer',
            name='question_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.questiontype'),
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
    ]
