# Generated by Django 4.0 on 2022-01-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_gridanswer_multiplechoiseanswer_questiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назва тесту')),
                ('quantity_questions', models.IntegerField(verbose_name='Кількість питань в тесті')),
                ('time_for_test', models.PositiveSmallIntegerField(default=60, verbose_name='Час тесту в хвилинах')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
            },
        ),
        migrations.RemoveField(
            model_name='multiplechoiseanswer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='shortanswer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='singlechoiseanswer',
            name='question_id',
        ),
        migrations.AlterModelOptions(
            name='answer_variants',
            options={'verbose_name': 'Варiанти відповіді', 'verbose_name_plural': 'Варiанти відповіді'},
        ),
        migrations.AddField(
            model_name='answer_variants',
            name='istrue1',
            field=models.BooleanField(default=False, verbose_name='Варiант 1 вірний'),
        ),
        migrations.AddField(
            model_name='answer_variants',
            name='istrue2',
            field=models.BooleanField(default=False, verbose_name='Варiант 1 вірний'),
        ),
        migrations.AddField(
            model_name='answer_variants',
            name='istrue3',
            field=models.BooleanField(default=False, verbose_name='Варiант 1 вірний'),
        ),
        migrations.AddField(
            model_name='answer_variants',
            name='istrue4',
            field=models.BooleanField(default=False, verbose_name='Варiант 1 вірний'),
        ),
        migrations.AddField(
            model_name='answer_variants',
            name='istrue5',
            field=models.BooleanField(default=False, verbose_name='Варiант 1 вірний'),
        ),
        migrations.AddField(
            model_name='answer_variants',
            name='istrue6',
            field=models.BooleanField(default=False, verbose_name='Варiант 1 вірний'),
        ),
        migrations.AddField(
            model_name='answer_variants',
            name='variant5',
            field=models.CharField(blank=True, max_length=100, verbose_name='Варiант 5'),
        ),
        migrations.AddField(
            model_name='answer_variants',
            name='variant6',
            field=models.CharField(blank=True, max_length=100, verbose_name='Варiант 6'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='answer', max_length=100),
        ),
        migrations.AlterField(
            model_name='answer_variants',
            name='variant1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Варiант 1'),
        ),
        migrations.AlterField(
            model_name='answer_variants',
            name='variant2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Варiант 2'),
        ),
        migrations.AlterField(
            model_name='answer_variants',
            name='variant3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Варiант 3'),
        ),
        migrations.AlterField(
            model_name='answer_variants',
            name='variant4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Варiант 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_variants',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.answer_variants'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(choices=[('S', 'Short_answer'), ('SC', 'Single_choise'), ('MC', 'Multiple_choise'), ('G', 'Insert_blanks')], default='S', max_length=2, verbose_name='Тип питання'),
        ),
        migrations.DeleteModel(
            name='GridAnswer',
        ),
        migrations.DeleteModel(
            name='MultipleChoiseAnswer',
        ),
        migrations.DeleteModel(
            name='ShortAnswer',
        ),
        migrations.DeleteModel(
            name='SingleChoiseAnswer',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.tests'),
        ),
        migrations.AddField(
            model_name='result',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.tests'),
        ),
    ]
