# Generated by Django 4.0 on 2022-01-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_tests_remove_multiplechoiseanswer_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_variants',
            name='istrue2',
            field=models.BooleanField(default=False, verbose_name='Варiант 2 вірний'),
        ),
        migrations.AlterField(
            model_name='answer_variants',
            name='istrue3',
            field=models.BooleanField(default=False, verbose_name='Варiант 3 вірний'),
        ),
        migrations.AlterField(
            model_name='answer_variants',
            name='istrue4',
            field=models.BooleanField(default=False, verbose_name='Варiант 4 вірний'),
        ),
        migrations.AlterField(
            model_name='answer_variants',
            name='istrue5',
            field=models.BooleanField(default=False, verbose_name='Варiант 5 вірний'),
        ),
        migrations.AlterField(
            model_name='answer_variants',
            name='istrue6',
            field=models.BooleanField(default=False, verbose_name='Варiант 6 вірний'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_variants',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.answer_variants'),
        ),
    ]
