# Generated by Django 4.0 on 2022-01-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_answer_variants_istrue2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testeduser',
            options={'ordering': ['last_name'], 'verbose_name': 'Користувач тесту', 'verbose_name_plural': 'Користувачі тесту'},
        ),
    ]
